// Vetro Look, GPL-3.0-or-later.
// Metadata, XMP sidecars, favourites and lens matching.
//
// Every case here maps to a real fixture on disk, generated by
// tests/make-fixtures.py. Nothing is mocked: the point is to prove that a file
// Lightroom wrote is read the way Lightroom wrote it.
#include "metaread.h"
#include "metacache.h"
#include "favourites.h"
#include "lensdb.h"
#include <windows.h>
#include <objbase.h>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <cmath>
#include <thread>
namespace fs=std::filesystem;

namespace{
int failures=0,checks=0;
void Check(bool ok,const std::string& name,const std::wstring& detail={}){
 checks++;
 if(!ok)failures++;
 std::wcout<<(ok?L"PASS ":L"FAIL ")<<std::wstring(name.begin(),name.end());
 if(!detail.empty())std::wcout<<L"   ["<<detail<<L"]";
 std::wcout<<L"\n";
}
std::wstring Show(const MetadataRecord& r){
 return L"rating="+std::to_wstring(r.rating)+L" has="+std::to_wstring(r.hasRating)+
        L" label="+r.label+L" src="+r.xmpSource+L" cam="+r.cameraModel+L" lens="+r.lens+
        L" warn="+r.warning;
}
}

int wmain(int argc,wchar_t** argv){
 if(argc<2){std::wcerr<<L"usage: metadata-test <fixture directory>\n";return 2;}
 CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);
 fs::path dir(argv[1]);

 // ---- A: an ordinary JPEG with EXIF -------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-a-plain.jpg").wstring());
  Check(r.ready,"A: plain JPEG parses",Show(r));
  Check(r.cameraModel.find(L"Z 6")!=std::wstring::npos,"A: camera model",r.cameraModel);
  Check(r.iso==400,"A: ISO",std::to_wstring(r.iso));
  Check(r.aperture>1.7&&r.aperture<1.9,"A: aperture",std::to_wstring(r.aperture));
  Check(r.shutter>0.0039&&r.shutter<0.0041,"A: shutter",std::to_wstring(r.shutter));
  Check(r.focalLength==50,"A: focal length",std::to_wstring(r.focalLength));
  Check(!r.dateTaken.empty(),"A: capture date",r.dateTaken);
  Check(!r.hasRating,"A: no rating where none was written",Show(r));
 }

 // ---- H: camera and lens ------------------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-a-plain.jpg").wstring());
  Check(r.lens.find(L"50mm")!=std::wstring::npos,"H: lens model",r.lens);
  Check(!r.author.empty()&&!r.copyright.empty(),"H: author and copyright",r.author+L" / "+r.copyright);
 }

 // ---- G: GPS ------------------------------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-g-gps.jpg").wstring());
  Check(r.hasGps,"G: GPS present",Show(r));
  Check(r.lat>35.6&&r.lat<35.7,"G: latitude",std::to_wstring(r.lat));
  Check(r.lon>139.6&&r.lon<139.8,"G: longitude",std::to_wstring(r.lon));
 }

 // ---- I: a file with no metadata at all ---------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-i-bare.jpg").wstring());
  Check(!r.hasRating&&r.label.empty(),"I: bare file has no rating or label",Show(r));
  Check(r.cameraModel.empty(),"I: bare file names no camera",r.cameraModel);
  Check(r.warning.empty(),"I: bare file is not an error",r.warning);
 }

 // ---- B/C: RAW-style host plus sidecar, rating 3 ------------------------
 {
  auto path=(dir/L"meta-c-rating3.jpg").wstring();
  Check(!SidecarFor(path).empty(),"B: sidecar located",SidecarFor(path));
  auto r=ReadMetadata(path);
  Check(r.hasRating&&r.rating==3,"C: xmp:Rating=3",Show(r));
  Check(r.xmpSource==L"sidecar","C: rating attributed to the sidecar",r.xmpSource);
  Check(!r.keywords.empty(),"C: dc:subject keywords",
        r.keywords.empty()?std::wstring():r.keywords.front());
 }

 // ---- D: rating 5 plus a label ------------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-d-rating5.jpg").wstring());
  Check(r.hasRating&&r.rating==5,"D: xmp:Rating=5",Show(r));
  Check(r.label==L"Select","D: xmp:Label",r.label);
 }

 // ---- E: rejected -------------------------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-e-rejected.jpg").wstring());
  Check(r.hasRating&&r.rating==-1,"E: xmp:Rating=-1 is a rejection, not zero stars",Show(r));
 }

 // ---- F: a label with no rating -----------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-f-label.jpg").wstring());
  Check(r.label==L"Red","F: xmp:Label without a rating",r.label);
  Check(!r.hasRating,"F: rating 0 is reported as absent, not as zero",Show(r));
 }

 // ---- embedded XMP, not a sidecar ---------------------------------------
 {
  auto r=ReadMetadata((dir/L"meta-k-embedded.jpg").wstring());
  Check(r.hasRating&&r.rating==4,"K: embedded XMP packet",Show(r));
  Check(r.xmpSource==L"embedded","K: attributed to the file itself",r.xmpSource);
 }

 // ---- J: a damaged sidecar must not cost the file its own metadata ------
 {
  auto path=(dir/L"meta-j-broken.jpg").wstring();
  auto r=ReadMetadata(path);
  Check(r.ready,"J: file still parses beside a broken sidecar",Show(r));
  Check(!r.hasRating,"J: no rating invented from damaged XMP",Show(r));
  Check(!r.cameraModel.empty(),"J: EXIF survives the damaged sidecar",r.cameraModel);
 }

 // ---- L: a changed sidecar invalidates the cache ------------------------
 {
  auto host=(dir/L"cache-host.jpg");
  fs::copy_file(dir/L"meta-c-rating3.jpg",host,fs::copy_options::overwrite_existing);
  auto sidecar=(dir/L"cache-host.xmp");
  fs::copy_file(dir/L"meta-c-rating3.xmp",sidecar,fs::copy_options::overwrite_existing);
  auto first=MetaCacheLookup(host.wstring());
  Check(first.valid&&first.rating==3,"L: first read caches rating 3",std::to_wstring(first.rating));
  auto again=MetaCacheGet(host.wstring());
  Check(again.valid,"L: unchanged file serves from cache",L"");
  // Overwrite the sidecar with the five-star one; the image is untouched.
  std::this_thread::sleep_for(std::chrono::milliseconds(40));
  fs::copy_file(dir/L"meta-d-rating5.xmp",sidecar,fs::copy_options::overwrite_existing);
  auto stale=MetaCacheGet(host.wstring());
  Check(!stale.valid,"L: changed sidecar invalidates the cached record",L"");
  auto refreshed=MetaCacheLookup(host.wstring());
  Check(refreshed.valid&&refreshed.rating==5,"L: rating refreshed without touching the image",
        std::to_wstring(refreshed.rating));
  fs::remove(host);fs::remove(sidecar);
 }

 // ---- K: favourites survive a rename on the same volume -----------------
 {
  auto original=(dir/L"fav-original.jpg");
  fs::copy_file(dir/L"meta-a-plain.jpg",original,fs::copy_options::overwrite_existing);
  FavouritesLoad();
  FavouriteSet(original.wstring(),false);       // start from a known state
  Check(!FavouriteGet(original.wstring()),"K: starts unfavourited",L"");
  FavouriteSet(original.wstring(),true);
  Check(FavouriteGet(original.wstring()),"K: favourite set",L"");
  Check(FolderHasFavourite(dir.wstring()),"K: folder reports a favourite",L"");

  auto renamed=(dir/L"fav-renamed.jpg");
  fs::remove(renamed);
  fs::rename(original,renamed);
  Check(FavouriteGet(renamed.wstring()),
        "K: favourite follows the file across a rename on NTFS",renamed.wstring());
  Check(!FavouriteGet(original.wstring()),"K: the old path is not favourited",L"");

  auto moved=(dir/L"moved");
  fs::create_directories(moved);
  auto destination=moved/L"fav-moved.jpg";
  fs::remove(destination);
  fs::rename(renamed,destination);
  Check(FavouriteGet(destination.wstring()),"K: favourite follows a move within the volume",
        destination.wstring());

  // Persistence: the store is flushed on every change, so a fresh read of the
  // file finds it.
  FavouritesFlush();
  auto listed=FavouritePaths();
  bool present=false;
  for(auto& p:listed)if(_wcsicmp(p.c_str(),destination.wstring().c_str())==0)present=true;
  Check(present,"K: appears in the Favourites collection",std::to_wstring(listed.size()));

  FavouriteSet(destination.wstring(),false);
  Check(!FavouriteGet(destination.wstring()),"K: favourite cleared",L"");
  listed=FavouritePaths();
  present=false;
  for(auto& p:listed)if(_wcsicmp(p.c_str(),destination.wstring().c_str())==0)present=true;
  Check(!present,"K: collection updates immediately on clear",L"");
  fs::remove(destination);fs::remove(moved);
 }

 // ---- Lensfun: coefficient extraction and interpolation ------------------
 //
 // These expected values were derived independently, by reading
 // third_party/lensfun-db/mil-nikon.xml with a separate script, not by
 // running this code. They check that the database is read and interpolated
 // the way Lensfun's own schema says it should be. They do NOT check that
 // applying these numbers to pixels matches Lensfun's output — that would
 // need the Lensfun library, which this project deliberately does not link.
 // See LICENSE_AUDIT.md and the "Lens correction" section of REPORT.md.
 {
  LensDbStart();
  for(int i=0;i<200&&!LensDbReady();i++)std::this_thread::sleep_for(std::chrono::milliseconds(50));
  auto info=LensLookup(L"NIKON CORPORATION",L"NIKON Z 6",L"NIKKOR Z 50mm f/1.8 S",50.0,1.8);
  // Not called `near`: windef.h still defines that as a 16-bit-era macro.
  auto expect=[&](double got,double want,double tolerance,const std::string& what){
   Check(std::fabs(got-want)<tolerance,what,
         L"got "+std::to_wstring(got)+L" want "+std::to_wstring(want));
  };
  Check(info.ready&&info.matched,"Lensfun: Nikkor Z 50mm matched",info.lensMatch+L" "+info.note);
  if(info.matched){
   Check(info.distortionModel==L"ptlens","Lensfun: distortion model is ptlens",info.distortionModel);
   expect(info.distortionA,-0.009,1e-9,"Lensfun: distortion a");
   expect(info.distortionB, 0.026,1e-9,"Lensfun: distortion b");
   expect(info.distortionC,-0.028,1e-9,"Lensfun: distortion c");
   expect(info.tcaRed, 1.0000289,1e-9,"Lensfun: TCA red scale");
   expect(info.tcaBlue,1.0000126,1e-9,"Lensfun: TCA blue scale");
   // f/1.8 is calibrated exactly, so the nearest-entry rule must land on it.
   expect(info.vignetteK1,-1.185965,1e-6,"Lensfun: vignetting k1 at f/1.8");
   expect(info.vignetteK2, 0.611494,1e-6,"Lensfun: vignetting k2 at f/1.8");
   expect(info.vignetteK3,-0.159837,1e-6,"Lensfun: vignetting k3 at f/1.8");
   // A different aperture must select a different calibration row.
   auto stopped=LensLookup(L"NIKON CORPORATION",L"NIKON Z 6",L"NIKKOR Z 50mm f/1.8 S",50.0,2.8);
   expect(stopped.vignetteK1,-0.160613,1e-6,"Lensfun: vignetting follows aperture to f/2.8");
   expect(stopped.distortionA,-0.009,1e-9,"Lensfun: distortion is aperture-independent");
  }
 }

 // ---- Lensfun ------------------------------------------------------------
 {
  LensDbStart();
  for(int i=0;i<200&&!LensDbReady();i++)std::this_thread::sleep_for(std::chrono::milliseconds(50));
  Check(LensDbReady(),"Lens database loaded",L"");
  Check(LensDbLensCount()>500,"Lens database has lenses",std::to_wstring(LensDbLensCount()));
  Check(LensDbCameraCount()>500,"Lens database has cameras",std::to_wstring(LensDbCameraCount()));
  auto info=LensLookup(L"NIKON CORPORATION",L"NIKON Z 6",L"NIKKOR Z 50mm f/1.8 S",50,1.8);
  Check(info.ready,"Lens lookup answers",info.note);
  Check(info.matched,"Lens matched",info.lensMatch+L" / "+info.note);
  if(info.matched){
   Check(info.lensMatch.find(L"50mm")!=std::wstring::npos,"Lens match names a 50mm",info.lensMatch);
   Check(info.distortion||info.vignetting||info.tca,"Some calibration is available",
         info.distortionModel+L" "+info.vignettingModel+L" "+info.tcaModel);
  }
  // A lens nobody has calibrated must report absence, not a fake profile.
  auto missing=LensLookup(L"Acme",L"Imaginary 1",L"Totally Invented 999mm f/0.1",999,0.1);
  Check(missing.ready&&!missing.matched,"Unknown lens reports no profile",missing.note);
  Check(!missing.distortion&&!missing.vignetting&&!missing.tca,
        "Unknown lens offers no corrections",L"");
 }


 // ---- favourites on a volume with no stable file identity ----------------
 //
 // Only runs when a second argument points at one. exFAT has no NTFS file id,
 // so the store falls back to (path, size, mtime): the favourite is keyed by
 // where the file is, and a file replaced at the same path must NOT inherit
 // the heart that belonged to its predecessor.
 if(argc>2){
  fs::path other(argv[2]);
  std::error_code ec;
  fs::create_directories(other,ec);
  auto sample=other/L"fat-favourite.jpg";
  fs::copy_file(dir/L"meta-a-plain.jpg",sample,fs::copy_options::overwrite_existing,ec);
  if(ec)Check(false,"FAT: fixture could not be copied to the test volume",other.wstring());
  else{
   FavouritesLoad();
   FavouriteSet(sample.wstring(),false);
   Check(!FavouriteGet(sample.wstring()),"FAT: starts unfavourited",sample.wstring());
   FavouriteSet(sample.wstring(),true);
   Check(FavouriteGet(sample.wstring()),"FAT: favourite set on a non-NTFS volume",L"");
   Check(FolderHasFavourite(other.wstring()),"FAT: folder reports a favourite",L"");

   auto listed=FavouritePaths();
   bool present=false;
   for(auto& q:listed)if(_wcsicmp(q.c_str(),sample.wstring().c_str())==0)present=true;
   Check(present,"FAT: appears in the Favourites collection",std::to_wstring(listed.size()));

   // The identity is (path, size, mtime). Replacing the file at the same path
   // with different content must break the match rather than hand the
   // favourite to a photograph nobody marked.
   std::this_thread::sleep_for(std::chrono::milliseconds(1200));
   fs::copy_file(dir/L"meta-g-gps.jpg",sample,fs::copy_options::overwrite_existing,ec);
   bool inherited=FavouriteGet(sample.wstring());
   Check(!inherited,"FAT: a different file at the same path does not inherit the favourite",
         inherited?L"WRONGLY INHERITED":L"correctly rejected");

   FavouriteSet(sample.wstring(),false);
   fs::remove(sample,ec);
  }
 }else std::wcout<<L"SKIP non-NTFS favourite fallback (no second argument given)\n";

 MetaCacheFlush();
 std::wcout<<L"\n"<<(failures?L"FAILED ":L"OK ")<<failures<<L" of "<<checks<<L" checks failed\n";
 CoUninitialize();
 return failures?1:0;
}
